# Generated by Django 3.0.4 on 2020-04-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='name',
            new_name='title',
        ),
    ]
