# Generated by Django 3.0.4 on 2020-04-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproduct', '0002_auto_20200412_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
